name: Build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cargo build --verbose

  #
  #
  tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Build tests
        run: |
          cargo install cargo-nextest --locked
          cargo test --no-run

      - name: Run tests
        run: |
          cargo nextest run

  #
  #
  cargo-audit:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-audit
        run: |
          cargo install cargo-audit

      - name: Run cargo audit
        run: cargo audit

  #
  #
  docker-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Build tests
        run: |
          cargo install cargo-nextest --locked
          cargo test --no-run --features docker-tests

      - name: Run Docker tests
        run: |
          cargo nextest run -F docker-tests

  #
  #
  native-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Build tests
        run: |
          cargo install cargo-nextest --locked
          cargo test --no-run --features native-tests,high-memory-tests

      - name: Install Pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Run Native tests
        run: |
          cargo nextest run -F native-tests,high-memory-tests
